version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
       build:
         command:
          - echo build entered in phase
          - mvn package
  post_build:
    commands:
      - echo Build generated successfully.
      - mv target/0.0.1-SNAPSHOT.war tomcat/webapps/0.0.1-SNAPSHOT.war
artifacts:
  files:
    - 0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
